@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}/api/v1

###  getLocation
GET {{host}}/location

### getWeatherByCity
# explame: GET {{host}}/weather/:city? (city optional)
GET {{host}}/current/TT

### getForecastByCity
# explame: GET {{host}}/forecast/:city? (city optional)
GET {{host}}/forecast

###
# explame: route not existent (404)
GET {{host}}/fore